{% set name = "flake8-use-fstring" %}
{% set version = "1.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/flake8-use-fstring-{{ version }}.tar.gz
  sha256: 6550bf722585eb97dffa8343b0f1c372101f5c4ab5b07ebf0edd1c79880cdd39

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - flake8 >=3
    - python >={{ python_min }}

test:
  imports:
    - flake8_use_fstring
  commands:
    - pip check
    - flake8 --version | grep use-fstring
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/MichaelKim0407/flake8-use-fstring
  summary: Flake8 plugin for string formatting style.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
